(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  (p = null) \/
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

(* Why3 assumption *)
Inductive P_in_subtree: (addr -> addr) -> addr -> addr -> Prop :=
  | Q_in_here :
      forall (Mptr:addr -> addr) (root:addr), ~ (null = root) ->
      P_in_subtree Mptr root root
  | Q_in_left :
      forall (Mptr:addr -> addr) (root:addr) (n:addr), ~ (null = root) ->
      P_in_subtree Mptr (Mptr (shift (shift root 0%Z) 0%Z)) n ->
      P_in_subtree Mptr root n
  | Q_in_right :
      forall (Mptr:addr -> addr) (root:addr) (n:addr), ~ (null = root) ->
      P_in_subtree Mptr (Mptr (shift (shift root 0%Z) 1%Z)) n ->
      P_in_subtree Mptr root n.

Axiom Q_in_subtree_descend_right :
  forall (Mptr:addr -> addr) (root:addr) (n:addr),
  let a := Mptr (shift (shift n 0%Z) 1%Z) in
  ~ (null = n) -> ~ (a = null) -> P_in_subtree Mptr root n ->
  P_in_subtree Mptr root a.

Axiom Q_in_subtree_descend_left :
  forall (Mptr:addr -> addr) (root:addr) (n:addr),
  let a := Mptr (shift (shift n 0%Z) 0%Z) in
  ~ (null = n) -> ~ (a = null) -> P_in_subtree Mptr root n ->
  P_in_subtree Mptr root a.

Axiom Q_in_subtree_split :
  forall (Mptr:addr -> addr) (root:addr) (m:addr),
  let a := shift root 0%Z in
  ~ (root = m) -> ~ (null = root) -> P_in_subtree Mptr root m ->
  P_in_subtree Mptr (Mptr (shift a 0%Z)) m \/
  P_in_subtree Mptr (Mptr (shift a 1%Z)) m.

Axiom Q_in_subtree_root_non_null :
  forall (Mptr:addr -> addr) (root:addr) (n:addr),
  P_in_subtree Mptr root n -> ~ (null = root).

(* Why3 assumption *)
Inductive P_parent_linked: (addr -> addr) -> addr -> addr -> Prop :=
  | Q_pl_null :
      forall (Mptr:addr -> addr) (ep:addr), P_parent_linked Mptr null ep
  | Q_pl_step :
      forall (Mptr:addr -> addr) (n:addr) (ep:addr),
      let a := shift n 0%Z in
      ~ (null = n) -> ((Mptr (shift a 2%Z)) = ep) ->
      P_parent_linked Mptr (Mptr (shift a 0%Z)) n ->
      P_parent_linked Mptr (Mptr (shift a 1%Z)) n ->
      P_parent_linked Mptr n ep.

Axiom Q_parent_linked_right :
  forall (Mptr:addr -> addr) (n:addr) (ep:addr), ~ (null = n) ->
  P_parent_linked Mptr n ep ->
  P_parent_linked Mptr (Mptr (shift (shift n 0%Z) 1%Z)) n.

Axiom Q_parent_linked_left :
  forall (Mptr:addr -> addr) (n:addr) (ep:addr), ~ (null = n) ->
  P_parent_linked Mptr n ep ->
  P_parent_linked Mptr (Mptr (shift (shift n 0%Z) 0%Z)) n.

Axiom Q_parent_linked_parent_matches :
  forall (Mptr:addr -> addr) (n:addr) (ep:addr), ~ (null = n) ->
  P_parent_linked Mptr n ep -> ((Mptr (shift (shift n 0%Z) 2%Z)) = ep).

Parameter L_key: addr -> Numbers.BinNums.Z.

(* Why3 assumption *)
Inductive P_bst_order: (addr -> addr) -> addr -> Numbers.BinNums.Z ->
  Numbers.BinNums.Z -> Prop :=
  | Q_bst_order_null :
      forall (Mptr:addr -> addr) (lo:Numbers.BinNums.Z)
        (hi:Numbers.BinNums.Z),
      P_bst_order Mptr null lo hi
  | Q_bst_order_step :
      forall (Mptr:addr -> addr) (n:addr) (lo:Numbers.BinNums.Z)
        (hi:Numbers.BinNums.Z),
      let x := L_key n in
      let a := shift n 0%Z in
      ~ (null = n) -> (lo < x)%Z -> (x < hi)%Z ->
      P_bst_order Mptr (Mptr (shift a 0%Z)) lo x ->
      P_bst_order Mptr (Mptr (shift a 1%Z)) x hi -> P_bst_order Mptr n lo hi.

Axiom Q_bst_order_right :
  forall (Mptr:addr -> addr) (n:addr) (lo:Numbers.BinNums.Z)
    (hi:Numbers.BinNums.Z),
  ~ (null = n) -> P_bst_order Mptr n lo hi ->
  P_bst_order Mptr (Mptr (shift (shift n 0%Z) 1%Z)) (L_key n) hi.

Axiom Q_bst_order_left :
  forall (Mptr:addr -> addr) (n:addr) (lo:Numbers.BinNums.Z)
    (hi:Numbers.BinNums.Z),
  ~ (null = n) -> P_bst_order Mptr n lo hi ->
  P_bst_order Mptr (Mptr (shift (shift n 0%Z) 0%Z)) lo (L_key n).

Axiom Q_bst_order_key_in_bounds :
  forall (Mptr:addr -> addr) (n:addr) (lo:Numbers.BinNums.Z)
    (hi:Numbers.BinNums.Z),
  let x := L_key n in
  ~ (null = n) -> P_bst_order Mptr n lo hi -> (lo < x)%Z /\ (x < hi)%Z.

(* Why3 assumption *)
Inductive P_wf_node: (Numbers.BinNums.Z -> Numbers.BinNums.Z) ->
  (addr -> addr) -> addr -> Numbers.BinNums.Z -> Prop :=
  | Q_wf_null :
      forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z)
        (Mptr:addr -> addr) (d:Numbers.BinNums.Z),
      (0%Z <= d)%Z -> P_wf_node Malloc Mptr null d
  | Q_wf_step :
      forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z)
        (Mptr:addr -> addr) (n:addr) (d:Numbers.BinNums.Z),
      let a := shift n 0%Z in
      let x := ((-1%Z)%Z + d)%Z in
      ~ (null = n) -> (0%Z < d)%Z -> valid_rd Malloc n 4%Z ->
      P_wf_node Malloc Mptr (Mptr (shift a 0%Z)) x ->
      P_wf_node Malloc Mptr (Mptr (shift a 1%Z)) x ->
      P_wf_node Malloc Mptr n d.

Axiom Q_wf_node_depth_positive :
  forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z) (Mptr:addr -> addr)
    (n:addr) (d:Numbers.BinNums.Z),
  ~ (null = n) -> P_wf_node Malloc Mptr n d -> (0%Z < d)%Z.

Axiom Q_wf_node_right :
  forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z) (Mptr:addr -> addr)
    (n:addr) (d:Numbers.BinNums.Z),
  ~ (null = n) -> (0%Z < d)%Z -> P_wf_node Malloc Mptr n d ->
  P_wf_node Malloc Mptr (Mptr (shift (shift n 0%Z) 1%Z)) ((-1%Z)%Z + d)%Z.

Axiom Q_wf_node_left :
  forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z) (Mptr:addr -> addr)
    (n:addr) (d:Numbers.BinNums.Z),
  ~ (null = n) -> (0%Z < d)%Z -> P_wf_node Malloc Mptr n d ->
  P_wf_node Malloc Mptr (Mptr (shift (shift n 0%Z) 0%Z)) ((-1%Z)%Z + d)%Z.

Axiom Q_wf_node_valid :
  forall (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z) (Mptr:addr -> addr)
    (n:addr) (d:Numbers.BinNums.Z),
  ~ (null = n) -> P_wf_node Malloc Mptr n d -> valid_rd Malloc n 4%Z.

(* Why3 goal *)
Theorem wp_goal :
  forall (t:addr -> addr) (a:addr) (a1:addr) (a2:addr), ~ (a2 = a1) ->
  P_parent_linked t a2 a -> P_in_subtree t a2 a1 ->
  P_in_subtree t a2 (t (shift (shift a1 0%Z) 2%Z)).
Proof.
intros t a a1 a2 h1 h2 h3.
(* h1 : a2 <> a1,  h2 : P_parent_linked t a2 a,  h3 : P_in_subtree t a2 a1 *)
(* Goal: P_in_subtree t a2 (t (shift (shift a1 0) 2))  (= parent of a1) *)
(* Generalize `ep` so the IH can carry a different expected parent. *)
revert a h2.
induction h3 as [Mptr root Hnn | Mptr root n Hnn hlr IH | Mptr root n Hnn hrr IH];
  intros ep hpl.
- (* Q_in_here: a2 = a1, contradicts h1 *)
  contradiction.
- (* Q_in_left: n is in root->left subtree *)
  pose proof (Q_parent_linked_left Mptr root ep Hnn hpl) as Hleft_pl.
  pose proof (Q_in_subtree_root_non_null _ _ _ hlr) as Hleft_nn.
  destruct (why_decidable_eq n (Mptr (shift (shift root 0%Z) 0%Z))) as [HeqL | HneqL].
  + (* n = root->left: parent(n) = root by parent_matches *)
    rewrite HeqL.
    pose proof (Q_parent_linked_parent_matches Mptr
      (Mptr (shift (shift root 0%Z) 0%Z)) root Hleft_nn Hleft_pl) as Hmatch.
    rewrite Hmatch.
    apply Q_in_here; exact Hnn.
  + (* n strictly deeper: IH + Q_in_left promotion *)
    assert (Hneq_sym: Mptr (shift (shift root 0%Z) 0%Z) <> n)
      by (intro H; apply HneqL; symmetry; exact H).
    apply Q_in_left; [ exact Hnn | ].
    apply (IH Hneq_sym root Hleft_pl).
- (* Q_in_right: symmetric *)
  pose proof (Q_parent_linked_right Mptr root ep Hnn hpl) as Hright_pl.
  pose proof (Q_in_subtree_root_non_null _ _ _ hrr) as Hright_nn.
  destruct (why_decidable_eq n (Mptr (shift (shift root 0%Z) 1%Z))) as [HeqR | HneqR].
  + rewrite HeqR.
    pose proof (Q_parent_linked_parent_matches Mptr
      (Mptr (shift (shift root 0%Z) 1%Z)) root Hright_nn Hright_pl) as Hmatch.
    rewrite Hmatch.
    apply Q_in_here; exact Hnn.
  + assert (Hneq_sym: Mptr (shift (shift root 0%Z) 1%Z) <> n)
      by (intro H; apply HneqR; symmetry; exact H).
    apply Q_in_right; [ exact Hnn | ].
    apply (IH Hneq_sym root Hright_pl).
Qed.

